version: '3.7'

volumes:
  db-data:

networks:
  db:

services:
  protofrontenddev:
    container_name: prototype-frontend-dev
    build:
      context: .
      dockerfile: Dockerfile
    image: prototype-frontend-dev-image
    depends_on:
      - projadmin
    # command: ["npm", "start"]


  projadmin:
    container_name: projectAdministration
    build: https://github.com/Michiel-s/Project-administration.git
    image: projectadministration-image
    env_file: "./devcontainer.env"
    volumes:
      - ./:/usr/local/project
    restart: always
    depends_on:
      - prototype-db
    ports:
      - "80:80"
    networks:
      - db

  prototype-db:
    container_name: prototype-db
    image: mariadb:10.4
    command: ["--sql-mode=ANSI,TRADITIONAL"]
    restart: unless-stopped
    env_file: ./devcontainer.env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - db

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - prototype-db
    ports:
      - "8080:80"
    networks:
      - db
    environment:
      - PMA_HOST=prototype-db # https://hub.docker.com/r/phpmyadmin/phpmyadmin/
